### ISSUE TITLE
Test servo code

### ISSUE THREAD

**Issue by HarlanHaller** [NorthernForce/RomiJavaBase#1]
The current code to run a servo feature/servo is untested. It should be tested before it is pulled into main.

**Comment by terrytompkins** [comment]
Hi Harlan - maybe we can test it on Tuesday, and then we can get a pull request submitted.  thank you!

**Comment by HarlanHaller** [comment]
code works on my robot but dose not work on Connor's batteries may be the issue

**Comment by HarlanHaller** [comment]
The problem with Connor's robot was identified and fixed it was not an issue with the code.

**Comment by HarlanHaller** [comment]
closing issue and creating pull request
